name: Deploy Maintenance mode

on:
  workflow_dispatch: # Manual button

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Crear archivo index.html con mensaje de mantenimiento
        run: |
          mkdir deploy
          echo '<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8" /><title>Sitio en Mantenimiento</title><style>body{background-color:#f0f0f0;font-family:Arial,sans-serif;text-align:center;padding-top:100px;color:#333;}</style></head><body><h1>Estamos realizando tareas de mantenimiento</h1><p>Vuelve a visitarnos en breve.</p></body></html>' > deploy/index.html

      - name: Instalar cliente FTP
        run: sudo apt-get update && sudo apt-get install -y ftp

      - name: Renombrar index.html actual y subir página de mantenimiento
        run: |
          ftp -n 147.93.88.21 <<EOF
          user u351649143 ${{ secrets.FTP_PASS }}
          binary
          rename index.html index_pause.html
          put deploy/index.html index.html
          quit
          EOF
