name: Restore Website from Maintenance

on:
  workflow_dispatch: # Manual button

jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar cliente FTP
        run: sudo apt-get update && sudo apt-get install -y ftp

      - name: Restaurar sitio web original
        run: |
          ftp -n 147.93.88.21 <<EOF
          user u351649143 ${{ secrets.FTP_PASS }}
          binary
          delete index.html
          rename index_pause.html index.html
          quit
          EOF
